version: '3'

services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  frontend:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      - TEMPERATURE_SERVICE_URL=http://temperature-service:3001
      - HUMIDITY_SERVICE_URL=http://humidity-service:3002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=strip-prefix"
    networks:
      - app-network

  temperature-service:
    build: ./temperature-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/temperatures
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.temperature.rule=PathPrefix(`/temperature`)"
      - "traefik.http.routers.temperature.entrypoints=web"
      - "traefik.http.services.temperature.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.strip-temp-prefix.stripprefix.prefixes=/temperature"
      - "traefik.http.routers.temperature.middlewares=strip-temp-prefix"
    networks:
      - app-network

  humidity-service:
    build: ./humidity-service
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/humidity
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.humidity.rule=PathPrefix(`/humidity`)"
      - "traefik.http.routers.humidity.entrypoints=web"
      - "traefik.http.services.humidity.loadbalancer.server.port=3002"
      - "traefik.http.middlewares.strip-humidity-prefix.stripprefix.prefixes=/humidity"
      - "traefik.http.routers.humidity.middlewares=strip-humidity-prefix"
    networks:
      - app-network

  # Les services de base de données restent identiques
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=humidity
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
  postgres-data:
